title: "Responsible Psychiatric Discharge Plans"
description: "Policy Advocacy Toolkit"
theme: jekyll-theme-cayman

# Social Preview & Interface Assets
og_image: "https://mmonfils.github.io/iowa-community-blueprints-template/assets/thumbnail.jpg"
favicon: "https://mmonfils.github.io/iowa-community-blueprints-template/assets/favicon.png"